In [2]:
import numpy as np
import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [4]:
data = np.genfromtxt('./breastCancerDataWisconsin.csv', delimiter=',')  # loading of data

In [5]:
data.shape

(570, 32)

In [6]:
data = data[1:, 1:] # Cleaning of data
data.shape

(569, 31)

In [9]:
opData = data[:, 0] # Extracting output
opData.shape

(569,)

In [10]:
ipData = data[:, 1:11]   #extracting input
ipData.shape

(569, 10)

In [11]:
# Splitting the data
ipTrain, ipTest, opTrain, opTest = train_test_split(ipData, opData, test_size=0.2, shuffle=True)

In [13]:
# Creating a model
model = LogisticRegression()

In [14]:
model.fit(ipTrain, opTrain)

/Users/subhasis/Desktop/devv/myenv/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
opPred = model.predict(ipTest)

In [16]:
opPred

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])

In [17]:
opTest

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1.,
       1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.])

In [28]:
correct = 0.0
wrong = 0.0
for i in range(opPred.shape[0]):
    if opPred[i] == opTest[i]:
        correct += 1
    else:
        wrong += 1
print "no of correct predictions: ", correct
print "no of wrong predictions: ", wrong

no of correct predictions:  105.0
no of wrong predictions:  9.0


In [31]:
accuracy = correct / opTest.shape[0] * 100
accuracy

92.10526315789474

In [32]:
# confusion matrix : 2x2 matrix for binary classification

In [38]:
tp, tn, fp, fn = 0.0, 0.0, 0.0, 0.0
for i in range(opPred.shape[0]):
    if opPred[i] == 1 and opTest[i] == 1:
        tp += 1
    elif opPred[i] == 0 and opTest[i] == 1:
        fn += 1
    elif opPred[i] == 0 and opTest[i] == 0:
        tn += 1
    else:
        fp += 1

print tp, tn, fp, fn
        

31.0 74.0 0.0 9.0


In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
confusion_matrix(opTest, opPred)

array([[74,  0],
       [ 9, 31]])

In [44]:
precision = tp / (tp + fp)
precision

1.0

In [45]:
recall = tp / (tp + fn)
recall

0.775

In [46]:
f1 = 2.0 * ((precision * recall) / (precision + recall))
f1

0.8732394366197184