In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = np.genfromtxt('test.csv', delimiter=',')
data = data[~np.isnan(data).any(axis=1)]
print data

[[8.4230200e+05 0.0000000e+00 1.7990000e+01 1.0380000e+01 1.2280000e+02
  1.0010000e+03 1.1840000e-01 2.7760000e-01 3.0010000e-01 1.4710000e-01]
 [8.4251700e+05 1.0000000e+00 2.0570000e+01 1.7770000e+01 1.3290000e+02
  1.3260000e+03 8.4740000e-02 7.8640000e-02 8.6900000e-02 7.0170000e-02]
 [8.4300903e+07 1.0000000e+00 1.9690000e+01 2.1250000e+01 1.3000000e+02
  1.2030000e+03 1.0960000e-01 1.5990000e-01 1.9740000e-01 1.2790000e-01]
 [8.4348301e+07 0.0000000e+00 1.1420000e+01 2.0380000e+01 7.7580000e+01
  3.8610000e+02 1.4250000e-01 2.8390000e-01 2.4140000e-01 1.0520000e-01]
 [8.4358402e+07 1.0000000e+00 2.0290000e+01 1.4340000e+01 1.3510000e+02
  1.2970000e+03 1.0030000e-01 1.3280000e-01 1.9800000e-01 1.0430000e-01]
 [8.4378600e+05 1.0000000e+00 2.4500000e+00 1.5700000e+01 8.2570000e+01
  4.7710000e+02 1.2780000e-01 1.7000000e-01 1.5780000e-01 8.0890000e-02]
 [8.4435900e+05 1.0000000e+00 1.8250000e+01 1.9980000e+01 1.1960000e+02
  1.0400000e+03 9.4630000e-02 1.0900000e-01 1.1270000e-01 

In [3]:
# Removing the id colummn
data = data[:, 1:]

In [4]:
# Normalize the data
maxVals = data.max(axis=0)
print "max vals", maxVals
maxVals[maxVals == 0] = 1
print "max vals", maxVals
data = data / maxVals
print data

max vals [1.000e+00 2.057e+01 2.182e+01 1.351e+02 1.326e+03 1.425e-01 2.839e-01
 3.001e-01 1.471e-01]
max vals [1.000e+00 2.057e+01 2.182e+01 1.351e+02 1.326e+03 1.425e-01 2.839e-01
 3.001e-01 1.471e-01]
[[0.         0.87457462 0.47571036 0.90895633 0.75490196 0.83087719
  0.97780909 1.         1.        ]
 [1.         1.         0.81439047 0.98371577 1.         0.59466667
  0.27699894 0.28957014 0.47702243]
 [1.         0.95721925 0.97387718 0.96225019 0.90723982 0.76912281
  0.56322649 0.65778074 0.86947655]
 [0.         0.55517744 0.9340055  0.5742413  0.29117647 1.
  1.         0.80439853 0.71515976]
 [1.         0.98638794 0.65719523 1.         0.97812971 0.70385965
  0.46777034 0.65978007 0.70904147]
 [1.         0.11910549 0.71952337 0.61117691 0.35980392 0.89684211
  0.5988024  0.52582473 0.54989803]
 [1.         0.88721439 0.91567369 0.88527017 0.78431373 0.66407018
  0.38393801 0.37554149 0.50305914]
 [0.         0.66650462 0.95462878 0.66765359 0.43582202 0.83438596
  0.5794

In [5]:
ipData = data[:, 1:]
opData = data[:, 0]

In [6]:
ipData

array([[0.87457462, 0.47571036, 0.90895633, 0.75490196, 0.83087719,
        0.97780909, 1.        , 1.        ],
       [1.        , 0.81439047, 0.98371577, 1.        , 0.59466667,
        0.27699894, 0.28957014, 0.47702243],
       [0.95721925, 0.97387718, 0.96225019, 0.90723982, 0.76912281,
        0.56322649, 0.65778074, 0.86947655],
       [0.55517744, 0.9340055 , 0.5742413 , 0.29117647, 1.        ,
        1.        , 0.80439853, 0.71515976],
       [0.98638794, 0.65719523, 1.        , 0.97812971, 0.70385965,
        0.46777034, 0.65978007, 0.70904147],
       [0.11910549, 0.71952337, 0.61117691, 0.35980392, 0.89684211,
        0.5988024 , 0.52582473, 0.54989803],
       [0.88721439, 0.91567369, 0.88527017, 0.78431373, 0.66407018,
        0.38393801, 0.37554149, 0.50305914],
       [0.66650462, 0.95462878, 0.66765359, 0.43582202, 0.83438596,
        0.57942938, 0.31209597, 0.40686608],
       [0.63198833, 1.        , 0.64766839, 0.39200603, 0.89333333,
        0.68052131, 0.619460

In [7]:
opData

array([0., 1., 1., 0., 1., 1., 1., 0., 1.])

In [8]:
ipData.shape

(9, 8)

In [9]:
opData.shape

(9,)

In [10]:
trainingPercent = 75
trainingFraction = 9 * 75 /100.0
print trainingFraction
trainingFraction = int(round(trainingFraction))
print trainingFraction
print type(trainingFraction)

6.75
7
<type 'int'>


In [11]:
traingInput = ipData[ 0: trainingFraction , :]
triningOp = opData[0 : trainingFraction]
testingInput = ipData[trainingFraction: , :]
testingOp = opData[trainingFraction:]

In [12]:
print traingInput.shape
print triningOp.shape
print testingInput.shape
print testingOp.shape

(7, 8)
(7,)
(2, 8)
(2,)


In [13]:
import sklearn as skl
from sklearn.model_selection import train_test_split

In [14]:
ip_train, ip_test, op_train, op_test = train_test_split(ipData, opData, train_size=0.75, shuffle=False)

/Users/subhasis/Desktop/devv/myenv/lib/python2.7/site-packages/sklearn/model_selection/_split.py:2178: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [15]:
print ip_train.shape
print op_train.shape
print ip_test.shape
print op_test.shape

(6, 8)
(6,)
(3, 8)
(3,)


In [16]:
# Demonstration of normalizing data

In [17]:
arr = np.array([[0,2,3,4], [0,6,7,8], [0,4,6,8]], dtype='float')
print arr

[[0. 2. 3. 4.]
 [0. 6. 7. 8.]
 [0. 4. 6. 8.]]


In [18]:
maxVals = arr.max(axis=0)
maxVals[maxVals == 0] = 1
print maxVals

[1. 6. 7. 8.]


In [19]:
arr = arr/ maxVals
print arr

[[0.         0.33333333 0.42857143 0.5       ]
 [0.         1.         1.         1.        ]
 [0.         0.66666667 0.85714286 1.        ]]
